# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30151acfb372a44befbe0200f9069310351eaba14fd010ffe23854e3438c975a379fd3c0bd081500b08166557a186d8af00531f62cab47fb8f08712bbd7e87b1

test:
  secret_key_base: 1a590b7656d2d100c5e67d442d6ced1d8fb50356d8f8e8c2e742e7c3e49f711dcce4a13696b3d490e40a495bd42e2852b86a3be6fae8b059a3d98f86537d98c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
